// Test script for n8n UGC webhook endpoint
const webhookUrl = 'https://zubaid.app.n8n.cloud/webhook/generate-ugc-content';

const testData = {
    productName: 'Wireless Fitness Tracker',
    targetAudience: 'Health and Fitness Enthusiasts',
    tone: 'excited',
    industry: 'Technology',
    contentType: 'social_post'
};

async function testWebhook() {
    console.log('🚀 Testing UGC Webhook Endpoint...');
    console.log('Endpoint:', webhookUrl);
    console.log('Test Data:', JSON.stringify(testData, null, 2));
    console.log('\n⏳ Sending request...');

    try {
        const response = await fetch(webhookUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(testData)
        });

        console.log('\n📊 Response Status:', response.status);
        console.log('Response Headers:', Object.fromEntries(response.headers.entries()));

        if (response.ok) {
            const result = await response.json();
            console.log('\n✅ Success! Generated UGC Content:');
            console.log(JSON.stringify(result, null, 2));
            
            // Parse and display the generated content nicely
            if (result.generated_content) {
                console.log('\n🎯 Generated Content Summary:');
                console.log('Generated by:', result.ai_model || 'Gemini 2.0 Flash');
                console.log('For Product:', result.product_name);
                console.log('Target Audience:', result.target_audience);
                console.log('Tone:', result.tone);
                console.log('\n📝 Raw Content:');
                console.log(result.generated_content);
            }
        } else {
            const errorText = await response.text();
            console.log('\n❌ Error Response:');
            console.log(errorText);
        }
    } catch (error) {
        console.log('\n💥 Request Failed:');
        console.log('Error:', error.message);
        
        if (error.code === 'ECONNREFUSED') {
            console.log('\n🔍 Troubleshooting Tips:');
            console.log('1. Make sure the n8n workflow is activated');
            console.log('2. Check if the webhook path is correct: /generate-ugc-content');
            console.log('3. Verify n8n instance is accessible at: https://zubaid.app.n8n.cloud');
        }
    }
}

// Run the test
testWebhook();